### ISSUE TITLE
Incomplete information on the Rules page

### ISSUE THREAD

**Issue by vladimir-kazakov** [dotnet-security-guard/roslyn-security-guard#39]
On the Rules page (/rules.htm), some descriptions contain a placeholder `{0}` instead of the actual data. For example:

> **Weak cipher algorithm**
> {0} is not considered a strong cipher for modern applications. Currently, NIST recommends the usage of AES block ciphers instead of {0}.

> **Weak hashing function**
> {0} is no longer considered a strong hashing algorithim for password storage and signature generation.

**Comment by h3xstream** [comment]
This is a tricky one to fix.. Their are multiple values possible. We did not want to create different description because the fix is the same.

I think the correct approach would be to add an attribute to the description file format that would contain the value to use when generating the static website.
